// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: openparallax/v1/pipeline.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PipelineService_ProcessMessage_FullMethodName  = "/openparallax.v1.PipelineService/ProcessMessage"
	PipelineService_ResolveApproval_FullMethodName = "/openparallax.v1.PipelineService/ResolveApproval"
	PipelineService_ReadMemory_FullMethodName      = "/openparallax.v1.PipelineService/ReadMemory"
	PipelineService_SearchMemory_FullMethodName    = "/openparallax.v1.PipelineService/SearchMemory"
	PipelineService_GetStatus_FullMethodName       = "/openparallax.v1.PipelineService/GetStatus"
	PipelineService_Shutdown_FullMethodName        = "/openparallax.v1.PipelineService/Shutdown"
)

// PipelineServiceClient is the client API for PipelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PipelineService handles Agent-to-Engine communication.
type PipelineServiceClient interface {
	// ProcessMessage runs a user message through the full pipeline.
	ProcessMessage(ctx context.Context, in *ProcessMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PipelineEvent], error)
	// ResolveApproval responds to a Tier 3 approval request.
	ResolveApproval(ctx context.Context, in *ApprovalResponse, opts ...grpc.CallOption) (*ApprovalAck, error)
	// ReadMemory reads a memory file.
	ReadMemory(ctx context.Context, in *MemoryReadRequest, opts ...grpc.CallOption) (*MemoryReadResponse, error)
	// SearchMemory searches memory via FTS5.
	SearchMemory(ctx context.Context, in *MemorySearchRequest, opts ...grpc.CallOption) (*MemorySearchResponse, error)
	// GetStatus returns agent status.
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Shutdown initiates graceful shutdown.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type pipelineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPipelineServiceClient(cc grpc.ClientConnInterface) PipelineServiceClient {
	return &pipelineServiceClient{cc}
}

func (c *pipelineServiceClient) ProcessMessage(ctx context.Context, in *ProcessMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PipelineEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PipelineService_ServiceDesc.Streams[0], PipelineService_ProcessMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessMessageRequest, PipelineEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelineService_ProcessMessageClient = grpc.ServerStreamingClient[PipelineEvent]

func (c *pipelineServiceClient) ResolveApproval(ctx context.Context, in *ApprovalResponse, opts ...grpc.CallOption) (*ApprovalAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalAck)
	err := c.cc.Invoke(ctx, PipelineService_ResolveApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) ReadMemory(ctx context.Context, in *MemoryReadRequest, opts ...grpc.CallOption) (*MemoryReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryReadResponse)
	err := c.cc.Invoke(ctx, PipelineService_ReadMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) SearchMemory(ctx context.Context, in *MemorySearchRequest, opts ...grpc.CallOption) (*MemorySearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemorySearchResponse)
	err := c.cc.Invoke(ctx, PipelineService_SearchMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PipelineService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, PipelineService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PipelineServiceServer is the server API for PipelineService service.
// All implementations must embed UnimplementedPipelineServiceServer
// for forward compatibility.
//
// PipelineService handles Agent-to-Engine communication.
type PipelineServiceServer interface {
	// ProcessMessage runs a user message through the full pipeline.
	ProcessMessage(*ProcessMessageRequest, grpc.ServerStreamingServer[PipelineEvent]) error
	// ResolveApproval responds to a Tier 3 approval request.
	ResolveApproval(context.Context, *ApprovalResponse) (*ApprovalAck, error)
	// ReadMemory reads a memory file.
	ReadMemory(context.Context, *MemoryReadRequest) (*MemoryReadResponse, error)
	// SearchMemory searches memory via FTS5.
	SearchMemory(context.Context, *MemorySearchRequest) (*MemorySearchResponse, error)
	// GetStatus returns agent status.
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	// Shutdown initiates graceful shutdown.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedPipelineServiceServer()
}

// UnimplementedPipelineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPipelineServiceServer struct{}

func (UnimplementedPipelineServiceServer) ProcessMessage(*ProcessMessageRequest, grpc.ServerStreamingServer[PipelineEvent]) error {
	return status.Error(codes.Unimplemented, "method ProcessMessage not implemented")
}
func (UnimplementedPipelineServiceServer) ResolveApproval(context.Context, *ApprovalResponse) (*ApprovalAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveApproval not implemented")
}
func (UnimplementedPipelineServiceServer) ReadMemory(context.Context, *MemoryReadRequest) (*MemoryReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadMemory not implemented")
}
func (UnimplementedPipelineServiceServer) SearchMemory(context.Context, *MemorySearchRequest) (*MemorySearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMemory not implemented")
}
func (UnimplementedPipelineServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPipelineServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPipelineServiceServer) mustEmbedUnimplementedPipelineServiceServer() {}
func (UnimplementedPipelineServiceServer) testEmbeddedByValue()                         {}

// UnsafePipelineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PipelineServiceServer will
// result in compilation errors.
type UnsafePipelineServiceServer interface {
	mustEmbedUnimplementedPipelineServiceServer()
}

func RegisterPipelineServiceServer(s grpc.ServiceRegistrar, srv PipelineServiceServer) {
	// If the following call panics, it indicates UnimplementedPipelineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PipelineService_ServiceDesc, srv)
}

func _PipelineService_ProcessMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PipelineServiceServer).ProcessMessage(m, &grpc.GenericServerStream[ProcessMessageRequest, PipelineEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelineService_ProcessMessageServer = grpc.ServerStreamingServer[PipelineEvent]

func _PipelineService_ResolveApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovalResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).ResolveApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_ResolveApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).ResolveApproval(ctx, req.(*ApprovalResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_ReadMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).ReadMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_ReadMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).ReadMemory(ctx, req.(*MemoryReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_SearchMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemorySearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).SearchMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_SearchMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).SearchMemory(ctx, req.(*MemorySearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PipelineService_ServiceDesc is the grpc.ServiceDesc for PipelineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PipelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openparallax.v1.PipelineService",
	HandlerType: (*PipelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveApproval",
			Handler:    _PipelineService_ResolveApproval_Handler,
		},
		{
			MethodName: "ReadMemory",
			Handler:    _PipelineService_ReadMemory_Handler,
		},
		{
			MethodName: "SearchMemory",
			Handler:    _PipelineService_SearchMemory_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PipelineService_GetStatus_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _PipelineService_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessMessage",
			Handler:       _PipelineService_ProcessMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "openparallax/v1/pipeline.proto",
}
