// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: openparallax/v1/pipeline.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PipelineEventType identifies the event category.
type PipelineEventType int32

const (
	PipelineEventType_PIPELINE_EVENT_UNSPECIFIED PipelineEventType = 0
	PipelineEventType_INTENT_PARSED              PipelineEventType = 1
	PipelineEventType_ACTIONS_PLANNED            PipelineEventType = 2
	PipelineEventType_SELF_EVAL_PASSED           PipelineEventType = 3
	PipelineEventType_SHIELD_VERDICT             PipelineEventType = 4
	PipelineEventType_ACTION_STARTED             PipelineEventType = 5
	PipelineEventType_ACTION_COMPLETED           PipelineEventType = 6
	PipelineEventType_ACTION_ARTIFACT            PipelineEventType = 7
	PipelineEventType_LLM_TOKEN                  PipelineEventType = 8
	PipelineEventType_COMPOSING                  PipelineEventType = 9
	PipelineEventType_RESPONSE_COMPLETE          PipelineEventType = 10
	PipelineEventType_APPROVAL_NEEDED            PipelineEventType = 11
	PipelineEventType_OTR_BLOCKED                PipelineEventType = 12
	PipelineEventType_ERROR                      PipelineEventType = 13
)

// Enum value maps for PipelineEventType.
var (
	PipelineEventType_name = map[int32]string{
		0:  "PIPELINE_EVENT_UNSPECIFIED",
		1:  "INTENT_PARSED",
		2:  "ACTIONS_PLANNED",
		3:  "SELF_EVAL_PASSED",
		4:  "SHIELD_VERDICT",
		5:  "ACTION_STARTED",
		6:  "ACTION_COMPLETED",
		7:  "ACTION_ARTIFACT",
		8:  "LLM_TOKEN",
		9:  "COMPOSING",
		10: "RESPONSE_COMPLETE",
		11: "APPROVAL_NEEDED",
		12: "OTR_BLOCKED",
		13: "ERROR",
	}
	PipelineEventType_value = map[string]int32{
		"PIPELINE_EVENT_UNSPECIFIED": 0,
		"INTENT_PARSED":              1,
		"ACTIONS_PLANNED":            2,
		"SELF_EVAL_PASSED":           3,
		"SHIELD_VERDICT":             4,
		"ACTION_STARTED":             5,
		"ACTION_COMPLETED":           6,
		"ACTION_ARTIFACT":            7,
		"LLM_TOKEN":                  8,
		"COMPOSING":                  9,
		"RESPONSE_COMPLETE":          10,
		"APPROVAL_NEEDED":            11,
		"OTR_BLOCKED":                12,
		"ERROR":                      13,
	}
)

func (x PipelineEventType) Enum() *PipelineEventType {
	p := new(PipelineEventType)
	*p = x
	return p
}

func (x PipelineEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_openparallax_v1_pipeline_proto_enumTypes[0].Descriptor()
}

func (PipelineEventType) Type() protoreflect.EnumType {
	return &file_openparallax_v1_pipeline_proto_enumTypes[0]
}

func (x PipelineEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineEventType.Descriptor instead.
func (PipelineEventType) EnumDescriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{0}
}

// ProcessMessageRequest is the main pipeline input.
type ProcessMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Mode          SessionMode            `protobuf:"varint,4,opt,name=mode,proto3,enum=openparallax.v1.SessionMode" json:"mode,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMessageRequest) Reset() {
	*x = ProcessMessageRequest{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMessageRequest) ProtoMessage() {}

func (x *ProcessMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMessageRequest.ProtoReflect.Descriptor instead.
func (*ProcessMessageRequest) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ProcessMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProcessMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ProcessMessageRequest) GetMode() SessionMode {
	if x != nil {
		return x.Mode
	}
	return SessionMode_SESSION_MODE_UNSPECIFIED
}

func (x *ProcessMessageRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// PipelineEvent is streamed back to the caller during pipeline execution.
type PipelineEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageId        string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	EventType        PipelineEventType      `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=openparallax.v1.PipelineEventType" json:"event_type,omitempty"`
	IntentParsed     *IntentParsed          `protobuf:"bytes,10,opt,name=intent_parsed,json=intentParsed,proto3" json:"intent_parsed,omitempty"`
	ActionsPlanned   *ActionsPlanned        `protobuf:"bytes,11,opt,name=actions_planned,json=actionsPlanned,proto3" json:"actions_planned,omitempty"`
	SelfEvalResult   *SelfEvalResult        `protobuf:"bytes,12,opt,name=self_eval_result,json=selfEvalResult,proto3" json:"self_eval_result,omitempty"`
	ShieldVerdict    *ShieldVerdict         `protobuf:"bytes,13,opt,name=shield_verdict,json=shieldVerdict,proto3" json:"shield_verdict,omitempty"`
	ActionStarted    *ActionStarted         `protobuf:"bytes,14,opt,name=action_started,json=actionStarted,proto3" json:"action_started,omitempty"`
	ActionCompleted  *ActionCompleted       `protobuf:"bytes,15,opt,name=action_completed,json=actionCompleted,proto3" json:"action_completed,omitempty"`
	ActionArtifact   *ActionArtifact        `protobuf:"bytes,16,opt,name=action_artifact,json=actionArtifact,proto3" json:"action_artifact,omitempty"`
	LlmToken         *LLMToken              `protobuf:"bytes,17,opt,name=llm_token,json=llmToken,proto3" json:"llm_token,omitempty"`
	ResponseComplete *ResponseComplete      `protobuf:"bytes,18,opt,name=response_complete,json=responseComplete,proto3" json:"response_complete,omitempty"`
	ApprovalNeeded   *ApprovalNeeded        `protobuf:"bytes,19,opt,name=approval_needed,json=approvalNeeded,proto3" json:"approval_needed,omitempty"`
	OtrBlocked       *OTRBlocked            `protobuf:"bytes,20,opt,name=otr_blocked,json=otrBlocked,proto3" json:"otr_blocked,omitempty"`
	PipelineError    *PipelineError         `protobuf:"bytes,21,opt,name=pipeline_error,json=pipelineError,proto3" json:"pipeline_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PipelineEvent) Reset() {
	*x = PipelineEvent{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineEvent) ProtoMessage() {}

func (x *PipelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineEvent.ProtoReflect.Descriptor instead.
func (*PipelineEvent) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *PipelineEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PipelineEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PipelineEvent) GetEventType() PipelineEventType {
	if x != nil {
		return x.EventType
	}
	return PipelineEventType_PIPELINE_EVENT_UNSPECIFIED
}

func (x *PipelineEvent) GetIntentParsed() *IntentParsed {
	if x != nil {
		return x.IntentParsed
	}
	return nil
}

func (x *PipelineEvent) GetActionsPlanned() *ActionsPlanned {
	if x != nil {
		return x.ActionsPlanned
	}
	return nil
}

func (x *PipelineEvent) GetSelfEvalResult() *SelfEvalResult {
	if x != nil {
		return x.SelfEvalResult
	}
	return nil
}

func (x *PipelineEvent) GetShieldVerdict() *ShieldVerdict {
	if x != nil {
		return x.ShieldVerdict
	}
	return nil
}

func (x *PipelineEvent) GetActionStarted() *ActionStarted {
	if x != nil {
		return x.ActionStarted
	}
	return nil
}

func (x *PipelineEvent) GetActionCompleted() *ActionCompleted {
	if x != nil {
		return x.ActionCompleted
	}
	return nil
}

func (x *PipelineEvent) GetActionArtifact() *ActionArtifact {
	if x != nil {
		return x.ActionArtifact
	}
	return nil
}

func (x *PipelineEvent) GetLlmToken() *LLMToken {
	if x != nil {
		return x.LlmToken
	}
	return nil
}

func (x *PipelineEvent) GetResponseComplete() *ResponseComplete {
	if x != nil {
		return x.ResponseComplete
	}
	return nil
}

func (x *PipelineEvent) GetApprovalNeeded() *ApprovalNeeded {
	if x != nil {
		return x.ApprovalNeeded
	}
	return nil
}

func (x *PipelineEvent) GetOtrBlocked() *OTRBlocked {
	if x != nil {
		return x.OtrBlocked
	}
	return nil
}

func (x *PipelineEvent) GetPipelineError() *PipelineError {
	if x != nil {
		return x.PipelineError
	}
	return nil
}

// IntentParsed is emitted when intent parsing completes.
type IntentParsed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          GoalType               `protobuf:"varint,1,opt,name=goal,proto3,enum=openparallax.v1.GoalType" json:"goal,omitempty"`
	PrimaryAction ActionType             `protobuf:"varint,2,opt,name=primary_action,json=primaryAction,proto3,enum=openparallax.v1.ActionType" json:"primary_action,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Destructive   bool                   `protobuf:"varint,4,opt,name=destructive,proto3" json:"destructive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentParsed) Reset() {
	*x = IntentParsed{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentParsed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentParsed) ProtoMessage() {}

func (x *IntentParsed) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentParsed.ProtoReflect.Descriptor instead.
func (*IntentParsed) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *IntentParsed) GetGoal() GoalType {
	if x != nil {
		return x.Goal
	}
	return GoalType_GOAL_TYPE_UNSPECIFIED
}

func (x *IntentParsed) GetPrimaryAction() ActionType {
	if x != nil {
		return x.PrimaryAction
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *IntentParsed) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *IntentParsed) GetDestructive() bool {
	if x != nil {
		return x.Destructive
	}
	return false
}

// ActionsPlanned is emitted when the agent finishes planning actions.
type ActionsPlanned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []ActionType           `protobuf:"varint,1,rep,packed,name=actions,proto3,enum=openparallax.v1.ActionType" json:"actions,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionsPlanned) Reset() {
	*x = ActionsPlanned{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsPlanned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsPlanned) ProtoMessage() {}

func (x *ActionsPlanned) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsPlanned.ProtoReflect.Descriptor instead.
func (*ActionsPlanned) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{3}
}

func (x *ActionsPlanned) GetActions() []ActionType {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ActionsPlanned) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// SelfEvalResult is emitted after Layer 0 self-check.
type SelfEvalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfEvalResult) Reset() {
	*x = SelfEvalResult{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfEvalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfEvalResult) ProtoMessage() {}

func (x *SelfEvalResult) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfEvalResult.ProtoReflect.Descriptor instead.
func (*SelfEvalResult) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{4}
}

func (x *SelfEvalResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *SelfEvalResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ShieldVerdict is emitted after Shield evaluation.
type ShieldVerdict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      VerdictDecision        `protobuf:"varint,1,opt,name=decision,proto3,enum=openparallax.v1.VerdictDecision" json:"decision,omitempty"`
	Tier          int32                  `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reasoning     string                 `protobuf:"bytes,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	ActionType    ActionType             `protobuf:"varint,5,opt,name=action_type,json=actionType,proto3,enum=openparallax.v1.ActionType" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShieldVerdict) Reset() {
	*x = ShieldVerdict{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShieldVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldVerdict) ProtoMessage() {}

func (x *ShieldVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldVerdict.ProtoReflect.Descriptor instead.
func (*ShieldVerdict) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{5}
}

func (x *ShieldVerdict) GetDecision() VerdictDecision {
	if x != nil {
		return x.Decision
	}
	return VerdictDecision_VERDICT_DECISION_UNSPECIFIED
}

func (x *ShieldVerdict) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *ShieldVerdict) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ShieldVerdict) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *ShieldVerdict) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

// ActionStarted is emitted when an action begins execution.
type ActionStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    ActionType             `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=openparallax.v1.ActionType" json:"action_type,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionStarted) Reset() {
	*x = ActionStarted{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStarted) ProtoMessage() {}

func (x *ActionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStarted.ProtoReflect.Descriptor instead.
func (*ActionStarted) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{6}
}

func (x *ActionStarted) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ActionStarted) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// ActionCompleted is emitted when an action finishes execution.
type ActionCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    ActionType             `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=openparallax.v1.ActionType" json:"action_type,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionCompleted) Reset() {
	*x = ActionCompleted{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCompleted) ProtoMessage() {}

func (x *ActionCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCompleted.ProtoReflect.Descriptor instead.
func (*ActionCompleted) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{7}
}

func (x *ActionCompleted) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ActionCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionCompleted) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// ActionArtifact is emitted when an action produces a viewable artifact.
type ActionArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionArtifact) Reset() {
	*x = ActionArtifact{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionArtifact) ProtoMessage() {}

func (x *ActionArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionArtifact.ProtoReflect.Descriptor instead.
func (*ActionArtifact) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{8}
}

func (x *ActionArtifact) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

// LLMToken carries a single streaming token from the LLM.
type LLMToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMToken) Reset() {
	*x = LLMToken{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMToken) ProtoMessage() {}

func (x *LLMToken) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMToken.ProtoReflect.Descriptor instead.
func (*LLMToken) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{9}
}

func (x *LLMToken) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ResponseComplete carries the full final response text.
type ResponseComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseComplete) Reset() {
	*x = ResponseComplete{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseComplete) ProtoMessage() {}

func (x *ResponseComplete) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseComplete.ProtoReflect.Descriptor instead.
func (*ResponseComplete) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseComplete) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ApprovalNeeded is emitted when Tier 3 human approval is required.
type ApprovalNeeded struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId       string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	Action           *ActionRequest         `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ShieldAssessment *Verdict               `protobuf:"bytes,3,opt,name=shield_assessment,json=shieldAssessment,proto3" json:"shield_assessment,omitempty"`
	ContextSummary   string                 `protobuf:"bytes,4,opt,name=context_summary,json=contextSummary,proto3" json:"context_summary,omitempty"`
	TimeoutAt        int64                  `protobuf:"varint,5,opt,name=timeout_at,json=timeoutAt,proto3" json:"timeout_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApprovalNeeded) Reset() {
	*x = ApprovalNeeded{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalNeeded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalNeeded) ProtoMessage() {}

func (x *ApprovalNeeded) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalNeeded.ProtoReflect.Descriptor instead.
func (*ApprovalNeeded) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{11}
}

func (x *ApprovalNeeded) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApprovalNeeded) GetAction() *ActionRequest {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ApprovalNeeded) GetShieldAssessment() *Verdict {
	if x != nil {
		return x.ShieldAssessment
	}
	return nil
}

func (x *ApprovalNeeded) GetContextSummary() string {
	if x != nil {
		return x.ContextSummary
	}
	return ""
}

func (x *ApprovalNeeded) GetTimeoutAt() int64 {
	if x != nil {
		return x.TimeoutAt
	}
	return 0
}

// OTRBlocked is emitted when an action is blocked in OTR mode.
type OTRBlocked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    ActionType             `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=openparallax.v1.ActionType" json:"action_type,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTRBlocked) Reset() {
	*x = OTRBlocked{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTRBlocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTRBlocked) ProtoMessage() {}

func (x *OTRBlocked) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTRBlocked.ProtoReflect.Descriptor instead.
func (*OTRBlocked) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{12}
}

func (x *OTRBlocked) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *OTRBlocked) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PipelineError is emitted when a pipeline stage fails.
type PipelineError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Recoverable   bool                   `protobuf:"varint,3,opt,name=recoverable,proto3" json:"recoverable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineError) Reset() {
	*x = PipelineError{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineError) ProtoMessage() {}

func (x *PipelineError) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineError.ProtoReflect.Descriptor instead.
func (*PipelineError) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{13}
}

func (x *PipelineError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PipelineError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PipelineError) GetRecoverable() bool {
	if x != nil {
		return x.Recoverable
	}
	return false
}

// ApprovalResponse carries the user's approval decision.
type ApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId    string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Approved      bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalResponse) Reset() {
	*x = ApprovalResponse{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalResponse) ProtoMessage() {}

func (x *ApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalResponse.ProtoReflect.Descriptor instead.
func (*ApprovalResponse) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{14}
}

func (x *ApprovalResponse) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApprovalResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApprovalResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

// ApprovalAck confirms receipt of an approval response.
type ApprovalAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalAck) Reset() {
	*x = ApprovalAck{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalAck) ProtoMessage() {}

func (x *ApprovalAck) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalAck.ProtoReflect.Descriptor instead.
func (*ApprovalAck) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{15}
}

func (x *ApprovalAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

// MemoryReadRequest asks for a specific memory file.
type MemoryReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileType      string                 `protobuf:"bytes,1,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryReadRequest) Reset() {
	*x = MemoryReadRequest{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryReadRequest) ProtoMessage() {}

func (x *MemoryReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryReadRequest.ProtoReflect.Descriptor instead.
func (*MemoryReadRequest) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{16}
}

func (x *MemoryReadRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

// MemoryReadResponse returns the content of a memory file.
type MemoryReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryReadResponse) Reset() {
	*x = MemoryReadResponse{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryReadResponse) ProtoMessage() {}

func (x *MemoryReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryReadResponse.ProtoReflect.Descriptor instead.
func (*MemoryReadResponse) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{17}
}

func (x *MemoryReadResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryReadResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// MemorySearchRequest performs FTS5 search across memory.
type MemorySearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemorySearchRequest) Reset() {
	*x = MemorySearchRequest{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySearchRequest) ProtoMessage() {}

func (x *MemorySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySearchRequest.ProtoReflect.Descriptor instead.
func (*MemorySearchRequest) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{18}
}

func (x *MemorySearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MemorySearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// MemorySearchResponse returns FTS5 search results.
type MemorySearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MemorySearchResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemorySearchResponse) Reset() {
	*x = MemorySearchResponse{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySearchResponse) ProtoMessage() {}

func (x *MemorySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySearchResponse.ProtoReflect.Descriptor instead.
func (*MemorySearchResponse) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{19}
}

func (x *MemorySearchResponse) GetResults() []*MemorySearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// MemorySearchResult is a single FTS5 search hit.
type MemorySearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Section       string                 `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemorySearchResult) Reset() {
	*x = MemorySearchResult{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySearchResult) ProtoMessage() {}

func (x *MemorySearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySearchResult.ProtoReflect.Descriptor instead.
func (*MemorySearchResult) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{20}
}

func (x *MemorySearchResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MemorySearchResult) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *MemorySearchResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *MemorySearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// StatusRequest asks for agent status.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{21}
}

// StatusResponse returns agent status.
type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentName       string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Model           string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	ShieldConnected bool                   `protobuf:"varint,3,opt,name=shield_connected,json=shieldConnected,proto3" json:"shield_connected,omitempty"`
	ShieldMaxTier   int32                  `protobuf:"varint,4,opt,name=shield_max_tier,json=shieldMaxTier,proto3" json:"shield_max_tier,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	SessionCount    int32                  `protobuf:"varint,6,opt,name=session_count,json=sessionCount,proto3" json:"session_count,omitempty"`
	ActionsToday    int32                  `protobuf:"varint,7,opt,name=actions_today,json=actionsToday,proto3" json:"actions_today,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{22}
}

func (x *StatusResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *StatusResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StatusResponse) GetShieldConnected() bool {
	if x != nil {
		return x.ShieldConnected
	}
	return false
}

func (x *StatusResponse) GetShieldMaxTier() int32 {
	if x != nil {
		return x.ShieldMaxTier
	}
	return 0
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetSessionCount() int32 {
	if x != nil {
		return x.SessionCount
	}
	return 0
}

func (x *StatusResponse) GetActionsToday() int32 {
	if x != nil {
		return x.ActionsToday
	}
	return 0
}

// ShutdownRequest initiates graceful shutdown.
type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{23}
}

// ShutdownResponse confirms shutdown status.
type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clean         bool                   `protobuf:"varint,1,opt,name=clean,proto3" json:"clean,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_pipeline_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_pipeline_proto_rawDescGZIP(), []int{24}
}

func (x *ShutdownResponse) GetClean() bool {
	if x != nil {
		return x.Clean
	}
	return false
}

var File_openparallax_v1_pipeline_proto protoreflect.FileDescriptor

const file_openparallax_v1_pipeline_proto_rawDesc = "" +
	"\n" +
	"\x1eopenparallax/v1/pipeline.proto\x12\x0fopenparallax.v1\x1a\x1bopenparallax/v1/types.proto\"\xb9\x01\n" +
	"\x15ProcessMessageRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x120\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1c.openparallax.v1.SessionModeR\x04mode\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\xe5\a\n" +
	"\rPipelineEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12A\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\".openparallax.v1.PipelineEventTypeR\teventType\x12B\n" +
	"\rintent_parsed\x18\n" +
	" \x01(\v2\x1d.openparallax.v1.IntentParsedR\fintentParsed\x12H\n" +
	"\x0factions_planned\x18\v \x01(\v2\x1f.openparallax.v1.ActionsPlannedR\x0eactionsPlanned\x12I\n" +
	"\x10self_eval_result\x18\f \x01(\v2\x1f.openparallax.v1.SelfEvalResultR\x0eselfEvalResult\x12E\n" +
	"\x0eshield_verdict\x18\r \x01(\v2\x1e.openparallax.v1.ShieldVerdictR\rshieldVerdict\x12E\n" +
	"\x0eaction_started\x18\x0e \x01(\v2\x1e.openparallax.v1.ActionStartedR\ractionStarted\x12K\n" +
	"\x10action_completed\x18\x0f \x01(\v2 .openparallax.v1.ActionCompletedR\x0factionCompleted\x12H\n" +
	"\x0faction_artifact\x18\x10 \x01(\v2\x1f.openparallax.v1.ActionArtifactR\x0eactionArtifact\x126\n" +
	"\tllm_token\x18\x11 \x01(\v2\x19.openparallax.v1.LLMTokenR\bllmToken\x12N\n" +
	"\x11response_complete\x18\x12 \x01(\v2!.openparallax.v1.ResponseCompleteR\x10responseComplete\x12H\n" +
	"\x0fapproval_needed\x18\x13 \x01(\v2\x1f.openparallax.v1.ApprovalNeededR\x0eapprovalNeeded\x12<\n" +
	"\votr_blocked\x18\x14 \x01(\v2\x1b.openparallax.v1.OTRBlockedR\n" +
	"otrBlocked\x12E\n" +
	"\x0epipeline_error\x18\x15 \x01(\v2\x1e.openparallax.v1.PipelineErrorR\rpipelineError\"\xc3\x01\n" +
	"\fIntentParsed\x12-\n" +
	"\x04goal\x18\x01 \x01(\x0e2\x19.openparallax.v1.GoalTypeR\x04goal\x12B\n" +
	"\x0eprimary_action\x18\x02 \x01(\x0e2\x1b.openparallax.v1.ActionTypeR\rprimaryAction\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\vdestructive\x18\x04 \x01(\bR\vdestructive\"]\n" +
	"\x0eActionsPlanned\x125\n" +
	"\aactions\x18\x01 \x03(\x0e2\x1b.openparallax.v1.ActionTypeR\aactions\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"@\n" +
	"\x0eSelfEvalResult\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xdd\x01\n" +
	"\rShieldVerdict\x12<\n" +
	"\bdecision\x18\x01 \x01(\x0e2 .openparallax.v1.VerdictDecisionR\bdecision\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\x05R\x04tier\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\tR\treasoning\x12<\n" +
	"\vaction_type\x18\x05 \x01(\x0e2\x1b.openparallax.v1.ActionTypeR\n" +
	"actionType\"g\n" +
	"\rActionStarted\x12<\n" +
	"\vaction_type\x18\x01 \x01(\x0e2\x1b.openparallax.v1.ActionTypeR\n" +
	"actionType\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\"\x83\x01\n" +
	"\x0fActionCompleted\x12<\n" +
	"\vaction_type\x18\x01 \x01(\x0e2\x1b.openparallax.v1.ActionTypeR\n" +
	"actionType\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"G\n" +
	"\x0eActionArtifact\x125\n" +
	"\bartifact\x18\x01 \x01(\v2\x19.openparallax.v1.ArtifactR\bartifact\"\x1e\n" +
	"\bLLMToken\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\",\n" +
	"\x10ResponseComplete\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xf8\x01\n" +
	"\x0eApprovalNeeded\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x126\n" +
	"\x06action\x18\x02 \x01(\v2\x1e.openparallax.v1.ActionRequestR\x06action\x12E\n" +
	"\x11shield_assessment\x18\x03 \x01(\v2\x18.openparallax.v1.VerdictR\x10shieldAssessment\x12'\n" +
	"\x0fcontext_summary\x18\x04 \x01(\tR\x0econtextSummary\x12\x1d\n" +
	"\n" +
	"timeout_at\x18\x05 \x01(\x03R\ttimeoutAt\"b\n" +
	"\n" +
	"OTRBlocked\x12<\n" +
	"\vaction_type\x18\x01 \x01(\x0e2\x1b.openparallax.v1.ActionTypeR\n" +
	"actionType\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"_\n" +
	"\rPipelineError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\vrecoverable\x18\x03 \x01(\bR\vrecoverable\"n\n" +
	"\x10ApprovalResponse\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\")\n" +
	"\vApprovalAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"0\n" +
	"\x11MemoryReadRequest\x12\x1b\n" +
	"\tfile_type\x18\x01 \x01(\tR\bfileType\"B\n" +
	"\x12MemoryReadResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"A\n" +
	"\x13MemorySearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"U\n" +
	"\x14MemorySearchResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.openparallax.v1.MemorySearchResultR\aresults\"r\n" +
	"\x12MemorySearchResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\asection\x18\x02 \x01(\tR\asection\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"\x0f\n" +
	"\rStatusRequest\"\x89\x02\n" +
	"\x0eStatusResponse\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12)\n" +
	"\x10shield_connected\x18\x03 \x01(\bR\x0fshieldConnected\x12&\n" +
	"\x0fshield_max_tier\x18\x04 \x01(\x05R\rshieldMaxTier\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12#\n" +
	"\rsession_count\x18\x06 \x01(\x05R\fsessionCount\x12#\n" +
	"\ractions_today\x18\a \x01(\x05R\factionsToday\"\x11\n" +
	"\x0fShutdownRequest\"(\n" +
	"\x10ShutdownResponse\x12\x14\n" +
	"\x05clean\x18\x01 \x01(\bR\x05clean*\xaa\x02\n" +
	"\x11PipelineEventType\x12\x1e\n" +
	"\x1aPIPELINE_EVENT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rINTENT_PARSED\x10\x01\x12\x13\n" +
	"\x0fACTIONS_PLANNED\x10\x02\x12\x14\n" +
	"\x10SELF_EVAL_PASSED\x10\x03\x12\x12\n" +
	"\x0eSHIELD_VERDICT\x10\x04\x12\x12\n" +
	"\x0eACTION_STARTED\x10\x05\x12\x14\n" +
	"\x10ACTION_COMPLETED\x10\x06\x12\x13\n" +
	"\x0fACTION_ARTIFACT\x10\a\x12\r\n" +
	"\tLLM_TOKEN\x10\b\x12\r\n" +
	"\tCOMPOSING\x10\t\x12\x15\n" +
	"\x11RESPONSE_COMPLETE\x10\n" +
	"\x12\x13\n" +
	"\x0fAPPROVAL_NEEDED\x10\v\x12\x0f\n" +
	"\vOTR_BLOCKED\x10\f\x12\t\n" +
	"\x05ERROR\x10\r2\x94\x04\n" +
	"\x0fPipelineService\x12Z\n" +
	"\x0eProcessMessage\x12&.openparallax.v1.ProcessMessageRequest\x1a\x1e.openparallax.v1.PipelineEvent0\x01\x12R\n" +
	"\x0fResolveApproval\x12!.openparallax.v1.ApprovalResponse\x1a\x1c.openparallax.v1.ApprovalAck\x12U\n" +
	"\n" +
	"ReadMemory\x12\".openparallax.v1.MemoryReadRequest\x1a#.openparallax.v1.MemoryReadResponse\x12[\n" +
	"\fSearchMemory\x12$.openparallax.v1.MemorySearchRequest\x1a%.openparallax.v1.MemorySearchResponse\x12L\n" +
	"\tGetStatus\x12\x1e.openparallax.v1.StatusRequest\x1a\x1f.openparallax.v1.StatusResponse\x12O\n" +
	"\bShutdown\x12 .openparallax.v1.ShutdownRequest\x1a!.openparallax.v1.ShutdownResponseB8Z6github.com/openparallax/openparallax/internal/types/pbb\x06proto3"

var (
	file_openparallax_v1_pipeline_proto_rawDescOnce sync.Once
	file_openparallax_v1_pipeline_proto_rawDescData []byte
)

func file_openparallax_v1_pipeline_proto_rawDescGZIP() []byte {
	file_openparallax_v1_pipeline_proto_rawDescOnce.Do(func() {
		file_openparallax_v1_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openparallax_v1_pipeline_proto_rawDesc), len(file_openparallax_v1_pipeline_proto_rawDesc)))
	})
	return file_openparallax_v1_pipeline_proto_rawDescData
}

var file_openparallax_v1_pipeline_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openparallax_v1_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_openparallax_v1_pipeline_proto_goTypes = []any{
	(PipelineEventType)(0),        // 0: openparallax.v1.PipelineEventType
	(*ProcessMessageRequest)(nil), // 1: openparallax.v1.ProcessMessageRequest
	(*PipelineEvent)(nil),         // 2: openparallax.v1.PipelineEvent
	(*IntentParsed)(nil),          // 3: openparallax.v1.IntentParsed
	(*ActionsPlanned)(nil),        // 4: openparallax.v1.ActionsPlanned
	(*SelfEvalResult)(nil),        // 5: openparallax.v1.SelfEvalResult
	(*ShieldVerdict)(nil),         // 6: openparallax.v1.ShieldVerdict
	(*ActionStarted)(nil),         // 7: openparallax.v1.ActionStarted
	(*ActionCompleted)(nil),       // 8: openparallax.v1.ActionCompleted
	(*ActionArtifact)(nil),        // 9: openparallax.v1.ActionArtifact
	(*LLMToken)(nil),              // 10: openparallax.v1.LLMToken
	(*ResponseComplete)(nil),      // 11: openparallax.v1.ResponseComplete
	(*ApprovalNeeded)(nil),        // 12: openparallax.v1.ApprovalNeeded
	(*OTRBlocked)(nil),            // 13: openparallax.v1.OTRBlocked
	(*PipelineError)(nil),         // 14: openparallax.v1.PipelineError
	(*ApprovalResponse)(nil),      // 15: openparallax.v1.ApprovalResponse
	(*ApprovalAck)(nil),           // 16: openparallax.v1.ApprovalAck
	(*MemoryReadRequest)(nil),     // 17: openparallax.v1.MemoryReadRequest
	(*MemoryReadResponse)(nil),    // 18: openparallax.v1.MemoryReadResponse
	(*MemorySearchRequest)(nil),   // 19: openparallax.v1.MemorySearchRequest
	(*MemorySearchResponse)(nil),  // 20: openparallax.v1.MemorySearchResponse
	(*MemorySearchResult)(nil),    // 21: openparallax.v1.MemorySearchResult
	(*StatusRequest)(nil),         // 22: openparallax.v1.StatusRequest
	(*StatusResponse)(nil),        // 23: openparallax.v1.StatusResponse
	(*ShutdownRequest)(nil),       // 24: openparallax.v1.ShutdownRequest
	(*ShutdownResponse)(nil),      // 25: openparallax.v1.ShutdownResponse
	(SessionMode)(0),              // 26: openparallax.v1.SessionMode
	(GoalType)(0),                 // 27: openparallax.v1.GoalType
	(ActionType)(0),               // 28: openparallax.v1.ActionType
	(VerdictDecision)(0),          // 29: openparallax.v1.VerdictDecision
	(*Artifact)(nil),              // 30: openparallax.v1.Artifact
	(*ActionRequest)(nil),         // 31: openparallax.v1.ActionRequest
	(*Verdict)(nil),               // 32: openparallax.v1.Verdict
}
var file_openparallax_v1_pipeline_proto_depIdxs = []int32{
	26, // 0: openparallax.v1.ProcessMessageRequest.mode:type_name -> openparallax.v1.SessionMode
	0,  // 1: openparallax.v1.PipelineEvent.event_type:type_name -> openparallax.v1.PipelineEventType
	3,  // 2: openparallax.v1.PipelineEvent.intent_parsed:type_name -> openparallax.v1.IntentParsed
	4,  // 3: openparallax.v1.PipelineEvent.actions_planned:type_name -> openparallax.v1.ActionsPlanned
	5,  // 4: openparallax.v1.PipelineEvent.self_eval_result:type_name -> openparallax.v1.SelfEvalResult
	6,  // 5: openparallax.v1.PipelineEvent.shield_verdict:type_name -> openparallax.v1.ShieldVerdict
	7,  // 6: openparallax.v1.PipelineEvent.action_started:type_name -> openparallax.v1.ActionStarted
	8,  // 7: openparallax.v1.PipelineEvent.action_completed:type_name -> openparallax.v1.ActionCompleted
	9,  // 8: openparallax.v1.PipelineEvent.action_artifact:type_name -> openparallax.v1.ActionArtifact
	10, // 9: openparallax.v1.PipelineEvent.llm_token:type_name -> openparallax.v1.LLMToken
	11, // 10: openparallax.v1.PipelineEvent.response_complete:type_name -> openparallax.v1.ResponseComplete
	12, // 11: openparallax.v1.PipelineEvent.approval_needed:type_name -> openparallax.v1.ApprovalNeeded
	13, // 12: openparallax.v1.PipelineEvent.otr_blocked:type_name -> openparallax.v1.OTRBlocked
	14, // 13: openparallax.v1.PipelineEvent.pipeline_error:type_name -> openparallax.v1.PipelineError
	27, // 14: openparallax.v1.IntentParsed.goal:type_name -> openparallax.v1.GoalType
	28, // 15: openparallax.v1.IntentParsed.primary_action:type_name -> openparallax.v1.ActionType
	28, // 16: openparallax.v1.ActionsPlanned.actions:type_name -> openparallax.v1.ActionType
	29, // 17: openparallax.v1.ShieldVerdict.decision:type_name -> openparallax.v1.VerdictDecision
	28, // 18: openparallax.v1.ShieldVerdict.action_type:type_name -> openparallax.v1.ActionType
	28, // 19: openparallax.v1.ActionStarted.action_type:type_name -> openparallax.v1.ActionType
	28, // 20: openparallax.v1.ActionCompleted.action_type:type_name -> openparallax.v1.ActionType
	30, // 21: openparallax.v1.ActionArtifact.artifact:type_name -> openparallax.v1.Artifact
	31, // 22: openparallax.v1.ApprovalNeeded.action:type_name -> openparallax.v1.ActionRequest
	32, // 23: openparallax.v1.ApprovalNeeded.shield_assessment:type_name -> openparallax.v1.Verdict
	28, // 24: openparallax.v1.OTRBlocked.action_type:type_name -> openparallax.v1.ActionType
	21, // 25: openparallax.v1.MemorySearchResponse.results:type_name -> openparallax.v1.MemorySearchResult
	1,  // 26: openparallax.v1.PipelineService.ProcessMessage:input_type -> openparallax.v1.ProcessMessageRequest
	15, // 27: openparallax.v1.PipelineService.ResolveApproval:input_type -> openparallax.v1.ApprovalResponse
	17, // 28: openparallax.v1.PipelineService.ReadMemory:input_type -> openparallax.v1.MemoryReadRequest
	19, // 29: openparallax.v1.PipelineService.SearchMemory:input_type -> openparallax.v1.MemorySearchRequest
	22, // 30: openparallax.v1.PipelineService.GetStatus:input_type -> openparallax.v1.StatusRequest
	24, // 31: openparallax.v1.PipelineService.Shutdown:input_type -> openparallax.v1.ShutdownRequest
	2,  // 32: openparallax.v1.PipelineService.ProcessMessage:output_type -> openparallax.v1.PipelineEvent
	16, // 33: openparallax.v1.PipelineService.ResolveApproval:output_type -> openparallax.v1.ApprovalAck
	18, // 34: openparallax.v1.PipelineService.ReadMemory:output_type -> openparallax.v1.MemoryReadResponse
	20, // 35: openparallax.v1.PipelineService.SearchMemory:output_type -> openparallax.v1.MemorySearchResponse
	23, // 36: openparallax.v1.PipelineService.GetStatus:output_type -> openparallax.v1.StatusResponse
	25, // 37: openparallax.v1.PipelineService.Shutdown:output_type -> openparallax.v1.ShutdownResponse
	32, // [32:38] is the sub-list for method output_type
	26, // [26:32] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_openparallax_v1_pipeline_proto_init() }
func file_openparallax_v1_pipeline_proto_init() {
	if File_openparallax_v1_pipeline_proto != nil {
		return
	}
	file_openparallax_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openparallax_v1_pipeline_proto_rawDesc), len(file_openparallax_v1_pipeline_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openparallax_v1_pipeline_proto_goTypes,
		DependencyIndexes: file_openparallax_v1_pipeline_proto_depIdxs,
		EnumInfos:         file_openparallax_v1_pipeline_proto_enumTypes,
		MessageInfos:      file_openparallax_v1_pipeline_proto_msgTypes,
	}.Build()
	File_openparallax_v1_pipeline_proto = out.File
	file_openparallax_v1_pipeline_proto_goTypes = nil
	file_openparallax_v1_pipeline_proto_depIdxs = nil
}
