// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: openparallax/v1/shield.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvaluateRequest accepts either simplified or MCP format.
type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolArgsJson  string                 `protobuf:"bytes,4,opt,name=tool_args_json,json=toolArgsJson,proto3" json:"tool_args_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_openparallax_v1_shield_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_shield_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_shield_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *EvaluateRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *EvaluateRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *EvaluateRequest) GetToolArgsJson() string {
	if x != nil {
		return x.ToolArgsJson
	}
	return ""
}

// EvaluateResponse returns the evaluation verdict.
type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       *Verdict               `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_openparallax_v1_shield_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_shield_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_shield_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateResponse) GetVerdict() *Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

// HealthRequest checks Shield health.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_openparallax_v1_shield_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_shield_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_shield_proto_rawDescGZIP(), []int{2}
}

// HealthResponse returns Shield health status.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	MaxTier       int32                  `protobuf:"varint,3,opt,name=max_tier,json=maxTier,proto3" json:"max_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_openparallax_v1_shield_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_shield_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_shield_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetMaxTier() int32 {
	if x != nil {
		return x.MaxTier
	}
	return 0
}

// ShieldStatusRequest asks for Shield operational status.
type ShieldStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShieldStatusRequest) Reset() {
	*x = ShieldStatusRequest{}
	mi := &file_openparallax_v1_shield_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShieldStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldStatusRequest) ProtoMessage() {}

func (x *ShieldStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_shield_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldStatusRequest.ProtoReflect.Descriptor instead.
func (*ShieldStatusRequest) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_shield_proto_rawDescGZIP(), []int{4}
}

// ShieldStatusResponse returns Shield operational details.
type ShieldStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OnnxLoaded       bool                   `protobuf:"varint,1,opt,name=onnx_loaded,json=onnxLoaded,proto3" json:"onnx_loaded,omitempty"`
	OnnxAccuracy     float64                `protobuf:"fixed64,2,opt,name=onnx_accuracy,json=onnxAccuracy,proto3" json:"onnx_accuracy,omitempty"`
	HeuristicRules   int32                  `protobuf:"varint,3,opt,name=heuristic_rules,json=heuristicRules,proto3" json:"heuristic_rules,omitempty"`
	LlmConnected     bool                   `protobuf:"varint,4,opt,name=llm_connected,json=llmConnected,proto3" json:"llm_connected,omitempty"`
	LlmProvider      string                 `protobuf:"bytes,5,opt,name=llm_provider,json=llmProvider,proto3" json:"llm_provider,omitempty"`
	LlmModel         string                 `protobuf:"bytes,6,opt,name=llm_model,json=llmModel,proto3" json:"llm_model,omitempty"`
	EvaluationsToday int64                  `protobuf:"varint,7,opt,name=evaluations_today,json=evaluationsToday,proto3" json:"evaluations_today,omitempty"`
	BlocksToday      int64                  `protobuf:"varint,8,opt,name=blocks_today,json=blocksToday,proto3" json:"blocks_today,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ShieldStatusResponse) Reset() {
	*x = ShieldStatusResponse{}
	mi := &file_openparallax_v1_shield_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShieldStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldStatusResponse) ProtoMessage() {}

func (x *ShieldStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_shield_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldStatusResponse.ProtoReflect.Descriptor instead.
func (*ShieldStatusResponse) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_shield_proto_rawDescGZIP(), []int{5}
}

func (x *ShieldStatusResponse) GetOnnxLoaded() bool {
	if x != nil {
		return x.OnnxLoaded
	}
	return false
}

func (x *ShieldStatusResponse) GetOnnxAccuracy() float64 {
	if x != nil {
		return x.OnnxAccuracy
	}
	return 0
}

func (x *ShieldStatusResponse) GetHeuristicRules() int32 {
	if x != nil {
		return x.HeuristicRules
	}
	return 0
}

func (x *ShieldStatusResponse) GetLlmConnected() bool {
	if x != nil {
		return x.LlmConnected
	}
	return false
}

func (x *ShieldStatusResponse) GetLlmProvider() string {
	if x != nil {
		return x.LlmProvider
	}
	return ""
}

func (x *ShieldStatusResponse) GetLlmModel() string {
	if x != nil {
		return x.LlmModel
	}
	return ""
}

func (x *ShieldStatusResponse) GetEvaluationsToday() int64 {
	if x != nil {
		return x.EvaluationsToday
	}
	return 0
}

func (x *ShieldStatusResponse) GetBlocksToday() int64 {
	if x != nil {
		return x.BlocksToday
	}
	return 0
}

var File_openparallax_v1_shield_proto protoreflect.FileDescriptor

const file_openparallax_v1_shield_proto_rawDesc = "" +
	"\n" +
	"\x1copenparallax/v1/shield.proto\x12\x0fopenparallax.v1\x1a\x1bopenparallax/v1/types.proto\"\x98\x01\n" +
	"\x0fEvaluateRequest\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12$\n" +
	"\x0etool_args_json\x18\x04 \x01(\tR\ftoolArgsJson\"F\n" +
	"\x10EvaluateResponse\x122\n" +
	"\averdict\x18\x01 \x01(\v2\x18.openparallax.v1.VerdictR\averdict\"\x0f\n" +
	"\rHealthRequest\"_\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\bmax_tier\x18\x03 \x01(\x05R\amaxTier\"\x15\n" +
	"\x13ShieldStatusRequest\"\xba\x02\n" +
	"\x14ShieldStatusResponse\x12\x1f\n" +
	"\vonnx_loaded\x18\x01 \x01(\bR\n" +
	"onnxLoaded\x12#\n" +
	"\ronnx_accuracy\x18\x02 \x01(\x01R\fonnxAccuracy\x12'\n" +
	"\x0fheuristic_rules\x18\x03 \x01(\x05R\x0eheuristicRules\x12#\n" +
	"\rllm_connected\x18\x04 \x01(\bR\fllmConnected\x12!\n" +
	"\fllm_provider\x18\x05 \x01(\tR\vllmProvider\x12\x1b\n" +
	"\tllm_model\x18\x06 \x01(\tR\bllmModel\x12+\n" +
	"\x11evaluations_today\x18\a \x01(\x03R\x10evaluationsToday\x12!\n" +
	"\fblocks_today\x18\b \x01(\x03R\vblocksToday2\x8b\x02\n" +
	"\rShieldService\x12O\n" +
	"\bEvaluate\x12 .openparallax.v1.EvaluateRequest\x1a!.openparallax.v1.EvaluateResponse\x12I\n" +
	"\x06Health\x12\x1e.openparallax.v1.HealthRequest\x1a\x1f.openparallax.v1.HealthResponse\x12^\n" +
	"\x0fGetShieldStatus\x12$.openparallax.v1.ShieldStatusRequest\x1a%.openparallax.v1.ShieldStatusResponseB8Z6github.com/openparallax/openparallax/internal/types/pbb\x06proto3"

var (
	file_openparallax_v1_shield_proto_rawDescOnce sync.Once
	file_openparallax_v1_shield_proto_rawDescData []byte
)

func file_openparallax_v1_shield_proto_rawDescGZIP() []byte {
	file_openparallax_v1_shield_proto_rawDescOnce.Do(func() {
		file_openparallax_v1_shield_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openparallax_v1_shield_proto_rawDesc), len(file_openparallax_v1_shield_proto_rawDesc)))
	})
	return file_openparallax_v1_shield_proto_rawDescData
}

var file_openparallax_v1_shield_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_openparallax_v1_shield_proto_goTypes = []any{
	(*EvaluateRequest)(nil),      // 0: openparallax.v1.EvaluateRequest
	(*EvaluateResponse)(nil),     // 1: openparallax.v1.EvaluateResponse
	(*HealthRequest)(nil),        // 2: openparallax.v1.HealthRequest
	(*HealthResponse)(nil),       // 3: openparallax.v1.HealthResponse
	(*ShieldStatusRequest)(nil),  // 4: openparallax.v1.ShieldStatusRequest
	(*ShieldStatusResponse)(nil), // 5: openparallax.v1.ShieldStatusResponse
	(*Verdict)(nil),              // 6: openparallax.v1.Verdict
}
var file_openparallax_v1_shield_proto_depIdxs = []int32{
	6, // 0: openparallax.v1.EvaluateResponse.verdict:type_name -> openparallax.v1.Verdict
	0, // 1: openparallax.v1.ShieldService.Evaluate:input_type -> openparallax.v1.EvaluateRequest
	2, // 2: openparallax.v1.ShieldService.Health:input_type -> openparallax.v1.HealthRequest
	4, // 3: openparallax.v1.ShieldService.GetShieldStatus:input_type -> openparallax.v1.ShieldStatusRequest
	1, // 4: openparallax.v1.ShieldService.Evaluate:output_type -> openparallax.v1.EvaluateResponse
	3, // 5: openparallax.v1.ShieldService.Health:output_type -> openparallax.v1.HealthResponse
	5, // 6: openparallax.v1.ShieldService.GetShieldStatus:output_type -> openparallax.v1.ShieldStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_openparallax_v1_shield_proto_init() }
func file_openparallax_v1_shield_proto_init() {
	if File_openparallax_v1_shield_proto != nil {
		return
	}
	file_openparallax_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openparallax_v1_shield_proto_rawDesc), len(file_openparallax_v1_shield_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openparallax_v1_shield_proto_goTypes,
		DependencyIndexes: file_openparallax_v1_shield_proto_depIdxs,
		MessageInfos:      file_openparallax_v1_shield_proto_msgTypes,
	}.Build()
	File_openparallax_v1_shield_proto = out.File
	file_openparallax_v1_shield_proto_goTypes = nil
	file_openparallax_v1_shield_proto_depIdxs = nil
}
