// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: openparallax/v1/shield.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShieldService_Evaluate_FullMethodName        = "/openparallax.v1.ShieldService/Evaluate"
	ShieldService_Health_FullMethodName          = "/openparallax.v1.ShieldService/Health"
	ShieldService_GetShieldStatus_FullMethodName = "/openparallax.v1.ShieldService/GetShieldStatus"
)

// ShieldServiceClient is the client API for ShieldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShieldService provides standalone Shield evaluation.
type ShieldServiceClient interface {
	// Evaluate evaluates a single action.
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	// Health checks Shield health.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// GetShieldStatus returns Shield operational status.
	GetShieldStatus(ctx context.Context, in *ShieldStatusRequest, opts ...grpc.CallOption) (*ShieldStatusResponse, error)
}

type shieldServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShieldServiceClient(cc grpc.ClientConnInterface) ShieldServiceClient {
	return &shieldServiceClient{cc}
}

func (c *shieldServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, ShieldService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shieldServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ShieldService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shieldServiceClient) GetShieldStatus(ctx context.Context, in *ShieldStatusRequest, opts ...grpc.CallOption) (*ShieldStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShieldStatusResponse)
	err := c.cc.Invoke(ctx, ShieldService_GetShieldStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShieldServiceServer is the server API for ShieldService service.
// All implementations must embed UnimplementedShieldServiceServer
// for forward compatibility.
//
// ShieldService provides standalone Shield evaluation.
type ShieldServiceServer interface {
	// Evaluate evaluates a single action.
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	// Health checks Shield health.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// GetShieldStatus returns Shield operational status.
	GetShieldStatus(context.Context, *ShieldStatusRequest) (*ShieldStatusResponse, error)
	mustEmbedUnimplementedShieldServiceServer()
}

// UnimplementedShieldServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShieldServiceServer struct{}

func (UnimplementedShieldServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedShieldServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedShieldServiceServer) GetShieldStatus(context.Context, *ShieldStatusRequest) (*ShieldStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShieldStatus not implemented")
}
func (UnimplementedShieldServiceServer) mustEmbedUnimplementedShieldServiceServer() {}
func (UnimplementedShieldServiceServer) testEmbeddedByValue()                       {}

// UnsafeShieldServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShieldServiceServer will
// result in compilation errors.
type UnsafeShieldServiceServer interface {
	mustEmbedUnimplementedShieldServiceServer()
}

func RegisterShieldServiceServer(s grpc.ServiceRegistrar, srv ShieldServiceServer) {
	// If the following call panics, it indicates UnimplementedShieldServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShieldService_ServiceDesc, srv)
}

func _ShieldService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShieldServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShieldService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShieldServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShieldService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShieldServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShieldService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShieldServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShieldService_GetShieldStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShieldStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShieldServiceServer).GetShieldStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShieldService_GetShieldStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShieldServiceServer).GetShieldStatus(ctx, req.(*ShieldStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShieldService_ServiceDesc is the grpc.ServiceDesc for ShieldService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShieldService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openparallax.v1.ShieldService",
	HandlerType: (*ShieldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _ShieldService_Evaluate_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ShieldService_Health_Handler,
		},
		{
			MethodName: "GetShieldStatus",
			Handler:    _ShieldService_GetShieldStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openparallax/v1/shield.proto",
}
