// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: openparallax/v1/types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActionType represents the category of action the agent can propose.
type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	// File operations
	ActionType_READ_FILE        ActionType = 1
	ActionType_WRITE_FILE       ActionType = 2
	ActionType_DELETE_FILE      ActionType = 3
	ActionType_MOVE_FILE        ActionType = 4
	ActionType_COPY_FILE        ActionType = 5
	ActionType_CREATE_DIRECTORY ActionType = 6
	ActionType_LIST_DIRECTORY   ActionType = 7
	ActionType_SEARCH_FILES     ActionType = 8
	// Shell
	ActionType_EXECUTE_COMMAND ActionType = 10
	// Communication
	ActionType_SEND_MESSAGE ActionType = 20
	ActionType_SEND_EMAIL   ActionType = 21
	// HTTP
	ActionType_HTTP_REQUEST ActionType = 30
	// Browser
	ActionType_BROWSER_NAVIGATE   ActionType = 40
	ActionType_BROWSER_CLICK      ActionType = 41
	ActionType_BROWSER_TYPE       ActionType = 42
	ActionType_BROWSER_EXTRACT    ActionType = 43
	ActionType_BROWSER_SCREENSHOT ActionType = 44
	// Schedule
	ActionType_CREATE_SCHEDULE ActionType = 50
	ActionType_DELETE_SCHEDULE ActionType = 51
	ActionType_LIST_SCHEDULES  ActionType = 52
	// Calendar
	ActionType_READ_CALENDAR ActionType = 60
	ActionType_CREATE_EVENT  ActionType = 61
	ActionType_UPDATE_EVENT  ActionType = 62
	ActionType_DELETE_EVENT  ActionType = 63
	// Git
	ActionType_GIT_STATUS   ActionType = 70
	ActionType_GIT_DIFF     ActionType = 71
	ActionType_GIT_COMMIT   ActionType = 72
	ActionType_GIT_PUSH     ActionType = 73
	ActionType_GIT_PULL     ActionType = 74
	ActionType_GIT_LOG      ActionType = 75
	ActionType_GIT_BRANCH   ActionType = 76
	ActionType_GIT_CHECKOUT ActionType = 77
	// Memory
	ActionType_MEMORY_WRITE  ActionType = 80
	ActionType_MEMORY_SEARCH ActionType = 81
	// Canvas
	ActionType_CANVAS_CREATE ActionType = 90
	ActionType_CANVAS_UPDATE ActionType = 91
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0:  "ACTION_TYPE_UNSPECIFIED",
		1:  "READ_FILE",
		2:  "WRITE_FILE",
		3:  "DELETE_FILE",
		4:  "MOVE_FILE",
		5:  "COPY_FILE",
		6:  "CREATE_DIRECTORY",
		7:  "LIST_DIRECTORY",
		8:  "SEARCH_FILES",
		10: "EXECUTE_COMMAND",
		20: "SEND_MESSAGE",
		21: "SEND_EMAIL",
		30: "HTTP_REQUEST",
		40: "BROWSER_NAVIGATE",
		41: "BROWSER_CLICK",
		42: "BROWSER_TYPE",
		43: "BROWSER_EXTRACT",
		44: "BROWSER_SCREENSHOT",
		50: "CREATE_SCHEDULE",
		51: "DELETE_SCHEDULE",
		52: "LIST_SCHEDULES",
		60: "READ_CALENDAR",
		61: "CREATE_EVENT",
		62: "UPDATE_EVENT",
		63: "DELETE_EVENT",
		70: "GIT_STATUS",
		71: "GIT_DIFF",
		72: "GIT_COMMIT",
		73: "GIT_PUSH",
		74: "GIT_PULL",
		75: "GIT_LOG",
		76: "GIT_BRANCH",
		77: "GIT_CHECKOUT",
		80: "MEMORY_WRITE",
		81: "MEMORY_SEARCH",
		90: "CANVAS_CREATE",
		91: "CANVAS_UPDATE",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"READ_FILE":               1,
		"WRITE_FILE":              2,
		"DELETE_FILE":             3,
		"MOVE_FILE":               4,
		"COPY_FILE":               5,
		"CREATE_DIRECTORY":        6,
		"LIST_DIRECTORY":          7,
		"SEARCH_FILES":            8,
		"EXECUTE_COMMAND":         10,
		"SEND_MESSAGE":            20,
		"SEND_EMAIL":              21,
		"HTTP_REQUEST":            30,
		"BROWSER_NAVIGATE":        40,
		"BROWSER_CLICK":           41,
		"BROWSER_TYPE":            42,
		"BROWSER_EXTRACT":         43,
		"BROWSER_SCREENSHOT":      44,
		"CREATE_SCHEDULE":         50,
		"DELETE_SCHEDULE":         51,
		"LIST_SCHEDULES":          52,
		"READ_CALENDAR":           60,
		"CREATE_EVENT":            61,
		"UPDATE_EVENT":            62,
		"DELETE_EVENT":            63,
		"GIT_STATUS":              70,
		"GIT_DIFF":                71,
		"GIT_COMMIT":              72,
		"GIT_PUSH":                73,
		"GIT_PULL":                74,
		"GIT_LOG":                 75,
		"GIT_BRANCH":              76,
		"GIT_CHECKOUT":            77,
		"MEMORY_WRITE":            80,
		"MEMORY_SEARCH":           81,
		"CANVAS_CREATE":           90,
		"CANVAS_UPDATE":           91,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_openparallax_v1_types_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_openparallax_v1_types_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{0}
}

// VerdictDecision is the security evaluation outcome.
type VerdictDecision int32

const (
	VerdictDecision_VERDICT_DECISION_UNSPECIFIED VerdictDecision = 0
	VerdictDecision_ALLOW                        VerdictDecision = 1
	VerdictDecision_BLOCK                        VerdictDecision = 2
	VerdictDecision_ESCALATE                     VerdictDecision = 3
)

// Enum value maps for VerdictDecision.
var (
	VerdictDecision_name = map[int32]string{
		0: "VERDICT_DECISION_UNSPECIFIED",
		1: "ALLOW",
		2: "BLOCK",
		3: "ESCALATE",
	}
	VerdictDecision_value = map[string]int32{
		"VERDICT_DECISION_UNSPECIFIED": 0,
		"ALLOW":                        1,
		"BLOCK":                        2,
		"ESCALATE":                     3,
	}
)

func (x VerdictDecision) Enum() *VerdictDecision {
	p := new(VerdictDecision)
	*p = x
	return p
}

func (x VerdictDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerdictDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_openparallax_v1_types_proto_enumTypes[1].Descriptor()
}

func (VerdictDecision) Type() protoreflect.EnumType {
	return &file_openparallax_v1_types_proto_enumTypes[1]
}

func (x VerdictDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerdictDecision.Descriptor instead.
func (VerdictDecision) EnumDescriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{1}
}

// SensitivityLevel is the data sensitivity classification.
type SensitivityLevel int32

const (
	SensitivityLevel_SENSITIVITY_UNSPECIFIED SensitivityLevel = 0
	SensitivityLevel_PUBLIC                  SensitivityLevel = 1
	SensitivityLevel_INTERNAL                SensitivityLevel = 2
	SensitivityLevel_CONFIDENTIAL            SensitivityLevel = 3
	SensitivityLevel_RESTRICTED              SensitivityLevel = 4
	SensitivityLevel_CRITICAL                SensitivityLevel = 5
)

// Enum value maps for SensitivityLevel.
var (
	SensitivityLevel_name = map[int32]string{
		0: "SENSITIVITY_UNSPECIFIED",
		1: "PUBLIC",
		2: "INTERNAL",
		3: "CONFIDENTIAL",
		4: "RESTRICTED",
		5: "CRITICAL",
	}
	SensitivityLevel_value = map[string]int32{
		"SENSITIVITY_UNSPECIFIED": 0,
		"PUBLIC":                  1,
		"INTERNAL":                2,
		"CONFIDENTIAL":            3,
		"RESTRICTED":              4,
		"CRITICAL":                5,
	}
)

func (x SensitivityLevel) Enum() *SensitivityLevel {
	p := new(SensitivityLevel)
	*p = x
	return p
}

func (x SensitivityLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SensitivityLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_openparallax_v1_types_proto_enumTypes[2].Descriptor()
}

func (SensitivityLevel) Type() protoreflect.EnumType {
	return &file_openparallax_v1_types_proto_enumTypes[2]
}

func (x SensitivityLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SensitivityLevel.Descriptor instead.
func (SensitivityLevel) EnumDescriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{2}
}

// GoalType represents the high-level category of user intent.
type GoalType int32

const (
	GoalType_GOAL_TYPE_UNSPECIFIED GoalType = 0
	GoalType_FILE_MANAGEMENT       GoalType = 1
	GoalType_CODE_EXECUTION        GoalType = 2
	GoalType_COMMUNICATION         GoalType = 3
	GoalType_INFORMATION_RETRIEVAL GoalType = 4
	GoalType_SCHEDULING            GoalType = 5
	GoalType_NOTE_TAKING           GoalType = 6
	GoalType_WEB_BROWSING          GoalType = 7
	GoalType_GIT_OPERATIONS        GoalType = 8
	GoalType_TEXT_PROCESSING       GoalType = 9
	GoalType_SYSTEM_MANAGEMENT     GoalType = 10
	GoalType_CREATIVE              GoalType = 11
	GoalType_CONVERSATION          GoalType = 12
	GoalType_CALENDAR              GoalType = 13
)

// Enum value maps for GoalType.
var (
	GoalType_name = map[int32]string{
		0:  "GOAL_TYPE_UNSPECIFIED",
		1:  "FILE_MANAGEMENT",
		2:  "CODE_EXECUTION",
		3:  "COMMUNICATION",
		4:  "INFORMATION_RETRIEVAL",
		5:  "SCHEDULING",
		6:  "NOTE_TAKING",
		7:  "WEB_BROWSING",
		8:  "GIT_OPERATIONS",
		9:  "TEXT_PROCESSING",
		10: "SYSTEM_MANAGEMENT",
		11: "CREATIVE",
		12: "CONVERSATION",
		13: "CALENDAR",
	}
	GoalType_value = map[string]int32{
		"GOAL_TYPE_UNSPECIFIED": 0,
		"FILE_MANAGEMENT":       1,
		"CODE_EXECUTION":        2,
		"COMMUNICATION":         3,
		"INFORMATION_RETRIEVAL": 4,
		"SCHEDULING":            5,
		"NOTE_TAKING":           6,
		"WEB_BROWSING":          7,
		"GIT_OPERATIONS":        8,
		"TEXT_PROCESSING":       9,
		"SYSTEM_MANAGEMENT":     10,
		"CREATIVE":              11,
		"CONVERSATION":          12,
		"CALENDAR":              13,
	}
)

func (x GoalType) Enum() *GoalType {
	p := new(GoalType)
	*p = x
	return p
}

func (x GoalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoalType) Descriptor() protoreflect.EnumDescriptor {
	return file_openparallax_v1_types_proto_enumTypes[3].Descriptor()
}

func (GoalType) Type() protoreflect.EnumType {
	return &file_openparallax_v1_types_proto_enumTypes[3]
}

func (x GoalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoalType.Descriptor instead.
func (GoalType) EnumDescriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{3}
}

// SessionMode controls what the agent can do in a session.
type SessionMode int32

const (
	SessionMode_SESSION_MODE_UNSPECIFIED SessionMode = 0
	SessionMode_NORMAL                   SessionMode = 1
	SessionMode_OTR                      SessionMode = 2
)

// Enum value maps for SessionMode.
var (
	SessionMode_name = map[int32]string{
		0: "SESSION_MODE_UNSPECIFIED",
		1: "NORMAL",
		2: "OTR",
	}
	SessionMode_value = map[string]int32{
		"SESSION_MODE_UNSPECIFIED": 0,
		"NORMAL":                   1,
		"OTR":                      2,
	}
)

func (x SessionMode) Enum() *SessionMode {
	p := new(SessionMode)
	*p = x
	return p
}

func (x SessionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_openparallax_v1_types_proto_enumTypes[4].Descriptor()
}

func (SessionMode) Type() protoreflect.EnumType {
	return &file_openparallax_v1_types_proto_enumTypes[4]
}

func (x SessionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionMode.Descriptor instead.
func (SessionMode) EnumDescriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{4}
}

// AuditEventType identifies the category of audit event.
type AuditEventType int32

const (
	AuditEventType_AUDIT_EVENT_UNSPECIFIED AuditEventType = 0
	AuditEventType_ACTION_PROPOSED         AuditEventType = 1
	AuditEventType_ACTION_EVALUATED        AuditEventType = 2
	AuditEventType_ACTION_APPROVED         AuditEventType = 3
	AuditEventType_ACTION_BLOCKED          AuditEventType = 4
	AuditEventType_ACTION_EXECUTED         AuditEventType = 5
	AuditEventType_ACTION_FAILED           AuditEventType = 6
	AuditEventType_SHIELD_ERROR            AuditEventType = 7
	AuditEventType_CANARY_VERIFIED         AuditEventType = 8
	AuditEventType_CANARY_MISSING          AuditEventType = 9
	AuditEventType_RATE_LIMIT_HIT          AuditEventType = 10
	AuditEventType_BUDGET_EXHAUSTED        AuditEventType = 11
	AuditEventType_SELF_PROTECTION         AuditEventType = 12
	AuditEventType_TRANSACTION_BEGIN       AuditEventType = 13
	AuditEventType_TRANSACTION_COMMIT      AuditEventType = 14
	AuditEventType_TRANSACTION_ROLLBACK    AuditEventType = 15
	AuditEventType_INTEGRITY_VIOLATION     AuditEventType = 16
	AuditEventType_SESSION_STARTED         AuditEventType = 17
	AuditEventType_SESSION_ENDED           AuditEventType = 18
)

// Enum value maps for AuditEventType.
var (
	AuditEventType_name = map[int32]string{
		0:  "AUDIT_EVENT_UNSPECIFIED",
		1:  "ACTION_PROPOSED",
		2:  "ACTION_EVALUATED",
		3:  "ACTION_APPROVED",
		4:  "ACTION_BLOCKED",
		5:  "ACTION_EXECUTED",
		6:  "ACTION_FAILED",
		7:  "SHIELD_ERROR",
		8:  "CANARY_VERIFIED",
		9:  "CANARY_MISSING",
		10: "RATE_LIMIT_HIT",
		11: "BUDGET_EXHAUSTED",
		12: "SELF_PROTECTION",
		13: "TRANSACTION_BEGIN",
		14: "TRANSACTION_COMMIT",
		15: "TRANSACTION_ROLLBACK",
		16: "INTEGRITY_VIOLATION",
		17: "SESSION_STARTED",
		18: "SESSION_ENDED",
	}
	AuditEventType_value = map[string]int32{
		"AUDIT_EVENT_UNSPECIFIED": 0,
		"ACTION_PROPOSED":         1,
		"ACTION_EVALUATED":        2,
		"ACTION_APPROVED":         3,
		"ACTION_BLOCKED":          4,
		"ACTION_EXECUTED":         5,
		"ACTION_FAILED":           6,
		"SHIELD_ERROR":            7,
		"CANARY_VERIFIED":         8,
		"CANARY_MISSING":          9,
		"RATE_LIMIT_HIT":          10,
		"BUDGET_EXHAUSTED":        11,
		"SELF_PROTECTION":         12,
		"TRANSACTION_BEGIN":       13,
		"TRANSACTION_COMMIT":      14,
		"TRANSACTION_ROLLBACK":    15,
		"INTEGRITY_VIOLATION":     16,
		"SESSION_STARTED":         17,
		"SESSION_ENDED":           18,
	}
)

func (x AuditEventType) Enum() *AuditEventType {
	p := new(AuditEventType)
	*p = x
	return p
}

func (x AuditEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_openparallax_v1_types_proto_enumTypes[5].Descriptor()
}

func (AuditEventType) Type() protoreflect.EnumType {
	return &file_openparallax_v1_types_proto_enumTypes[5]
}

func (x AuditEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEventType.Descriptor instead.
func (AuditEventType) EnumDescriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{5}
}

// Verdict is the complete evaluation result from Shield.
type Verdict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      VerdictDecision        `protobuf:"varint,1,opt,name=decision,proto3,enum=openparallax.v1.VerdictDecision" json:"decision,omitempty"`
	Tier          int32                  `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reasoning     string                 `protobuf:"bytes,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	ActionHash    string                 `protobuf:"bytes,5,opt,name=action_hash,json=actionHash,proto3" json:"action_hash,omitempty"`
	EvaluatedAt   int64                  `protobuf:"varint,6,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	mi := &file_openparallax_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Verdict) GetDecision() VerdictDecision {
	if x != nil {
		return x.Decision
	}
	return VerdictDecision_VERDICT_DECISION_UNSPECIFIED
}

func (x *Verdict) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *Verdict) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Verdict) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *Verdict) GetActionHash() string {
	if x != nil {
		return x.ActionHash
	}
	return ""
}

func (x *Verdict) GetEvaluatedAt() int64 {
	if x != nil {
		return x.EvaluatedAt
	}
	return 0
}

func (x *Verdict) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// ActionRequest represents a proposed action from the agent.
type ActionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Type               ActionType             `protobuf:"varint,2,opt,name=type,proto3,enum=openparallax.v1.ActionType" json:"type,omitempty"`
	Payload            map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PayloadJson        string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Hash               string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	DataClassification *DataClassification    `protobuf:"bytes,6,opt,name=data_classification,json=dataClassification,proto3" json:"data_classification,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_openparallax_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *ActionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ActionRequest) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ActionRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ActionRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *ActionRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ActionRequest) GetDataClassification() *DataClassification {
	if x != nil {
		return x.DataClassification
	}
	return nil
}

// DataClassification is the IFC tag attached to data flowing through the pipeline.
type DataClassification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sensitivity   SensitivityLevel       `protobuf:"varint,1,opt,name=sensitivity,proto3,enum=openparallax.v1.SensitivityLevel" json:"sensitivity,omitempty"`
	SourcePath    string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataClassification) Reset() {
	*x = DataClassification{}
	mi := &file_openparallax_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataClassification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataClassification) ProtoMessage() {}

func (x *DataClassification) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataClassification.ProtoReflect.Descriptor instead.
func (*DataClassification) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *DataClassification) GetSensitivity() SensitivityLevel {
	if x != nil {
		return x.Sensitivity
	}
	return SensitivityLevel_SENSITIVITY_UNSPECIFIED
}

func (x *DataClassification) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *DataClassification) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// StructuredIntent is the output of the intent parser.
type StructuredIntent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          GoalType               `protobuf:"varint,1,opt,name=goal,proto3,enum=openparallax.v1.GoalType" json:"goal,omitempty"`
	PrimaryAction ActionType             `protobuf:"varint,2,opt,name=primary_action,json=primaryAction,proto3,enum=openparallax.v1.ActionType" json:"primary_action,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Destructive   bool                   `protobuf:"varint,5,opt,name=destructive,proto3" json:"destructive,omitempty"`
	Sensitivity   SensitivityLevel       `protobuf:"varint,6,opt,name=sensitivity,proto3,enum=openparallax.v1.SensitivityLevel" json:"sensitivity,omitempty"`
	RawInput      string                 `protobuf:"bytes,7,opt,name=raw_input,json=rawInput,proto3" json:"raw_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredIntent) Reset() {
	*x = StructuredIntent{}
	mi := &file_openparallax_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredIntent) ProtoMessage() {}

func (x *StructuredIntent) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredIntent.ProtoReflect.Descriptor instead.
func (*StructuredIntent) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *StructuredIntent) GetGoal() GoalType {
	if x != nil {
		return x.Goal
	}
	return GoalType_GOAL_TYPE_UNSPECIFIED
}

func (x *StructuredIntent) GetPrimaryAction() ActionType {
	if x != nil {
		return x.PrimaryAction
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *StructuredIntent) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *StructuredIntent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *StructuredIntent) GetDestructive() bool {
	if x != nil {
		return x.Destructive
	}
	return false
}

func (x *StructuredIntent) GetSensitivity() SensitivityLevel {
	if x != nil {
		return x.Sensitivity
	}
	return SensitivityLevel_SENSITIVITY_UNSPECIFIED
}

func (x *StructuredIntent) GetRawInput() string {
	if x != nil {
		return x.RawInput
	}
	return ""
}

// ActionResult is the outcome of executing an action.
type ActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Artifact      *Artifact              `protobuf:"bytes,6,opt,name=artifact,proto3" json:"artifact,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_openparallax_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *ActionResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ActionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ActionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ActionResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ActionResult) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *ActionResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Artifact is a viewable output produced by an action.
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	PreviewType   string                 `protobuf:"bytes,8,opt,name=preview_type,json=previewType,proto3" json:"preview_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_openparallax_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Artifact) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Artifact) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Artifact) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Artifact) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Artifact) GetPreviewType() string {
	if x != nil {
		return x.PreviewType
	}
	return ""
}

// AuditEntry is a single audit log entry.
type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventType     AuditEventType         `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=openparallax.v1.AuditEventType" json:"event_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,5,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	DetailsJson   string                 `protobuf:"bytes,6,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	PreviousHash  string                 `protobuf:"bytes,7,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	Hash          string                 `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"`
	Otr           bool                   `protobuf:"varint,9,opt,name=otr,proto3" json:"otr,omitempty"`
	Source        string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_openparallax_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_openparallax_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_openparallax_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetEventType() AuditEventType {
	if x != nil {
		return x.EventType
	}
	return AuditEventType_AUDIT_EVENT_UNSPECIFIED
}

func (x *AuditEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuditEntry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuditEntry) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *AuditEntry) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

func (x *AuditEntry) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *AuditEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *AuditEntry) GetOtr() bool {
	if x != nil {
		return x.Otr
	}
	return false
}

func (x *AuditEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_openparallax_v1_types_proto protoreflect.FileDescriptor

const file_openparallax_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1bopenparallax/v1/types.proto\x12\x0fopenparallax.v1\"\xfc\x01\n" +
	"\aVerdict\x12<\n" +
	"\bdecision\x18\x01 \x01(\x0e2 .openparallax.v1.VerdictDecisionR\bdecision\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\x05R\x04tier\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\tR\treasoning\x12\x1f\n" +
	"\vaction_hash\x18\x05 \x01(\tR\n" +
	"actionHash\x12!\n" +
	"\fevaluated_at\x18\x06 \x01(\x03R\vevaluatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\"\xef\x02\n" +
	"\rActionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.openparallax.v1.ActionTypeR\x04type\x12E\n" +
	"\apayload\x18\x03 \x03(\v2+.openparallax.v1.ActionRequest.PayloadEntryR\apayload\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12T\n" +
	"\x13data_classification\x18\x06 \x01(\v2#.openparallax.v1.DataClassificationR\x12dataClassification\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\x12DataClassification\x12C\n" +
	"\vsensitivity\x18\x01 \x01(\x0e2!.openparallax.v1.SensitivityLevelR\vsensitivity\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\xbb\x03\n" +
	"\x10StructuredIntent\x12-\n" +
	"\x04goal\x18\x01 \x01(\x0e2\x19.openparallax.v1.GoalTypeR\x04goal\x12B\n" +
	"\x0eprimary_action\x18\x02 \x01(\x0e2\x1b.openparallax.v1.ActionTypeR\rprimaryAction\x12Q\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v21.openparallax.v1.StructuredIntent.ParametersEntryR\n" +
	"parameters\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\vdestructive\x18\x05 \x01(\bR\vdestructive\x12C\n" +
	"\vsensitivity\x18\x06 \x01(\x0e2!.openparallax.v1.SensitivityLevelR\vsensitivity\x12\x1b\n" +
	"\traw_input\x18\a \x01(\tR\brawInput\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x01\n" +
	"\fActionResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x125\n" +
	"\bartifact\x18\x06 \x01(\v2\x19.openparallax.v1.ArtifactR\bartifact\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\"\xd0\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12!\n" +
	"\fpreview_type\x18\b \x01(\tR\vpreviewType\"\xc0\x02\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x1f.openparallax.v1.AuditEventTypeR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vaction_type\x18\x05 \x01(\tR\n" +
	"actionType\x12!\n" +
	"\fdetails_json\x18\x06 \x01(\tR\vdetailsJson\x12#\n" +
	"\rprevious_hash\x18\a \x01(\tR\fpreviousHash\x12\x12\n" +
	"\x04hash\x18\b \x01(\tR\x04hash\x12\x10\n" +
	"\x03otr\x18\t \x01(\bR\x03otr\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source*\xaf\x05\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tREAD_FILE\x10\x01\x12\x0e\n" +
	"\n" +
	"WRITE_FILE\x10\x02\x12\x0f\n" +
	"\vDELETE_FILE\x10\x03\x12\r\n" +
	"\tMOVE_FILE\x10\x04\x12\r\n" +
	"\tCOPY_FILE\x10\x05\x12\x14\n" +
	"\x10CREATE_DIRECTORY\x10\x06\x12\x12\n" +
	"\x0eLIST_DIRECTORY\x10\a\x12\x10\n" +
	"\fSEARCH_FILES\x10\b\x12\x13\n" +
	"\x0fEXECUTE_COMMAND\x10\n" +
	"\x12\x10\n" +
	"\fSEND_MESSAGE\x10\x14\x12\x0e\n" +
	"\n" +
	"SEND_EMAIL\x10\x15\x12\x10\n" +
	"\fHTTP_REQUEST\x10\x1e\x12\x14\n" +
	"\x10BROWSER_NAVIGATE\x10(\x12\x11\n" +
	"\rBROWSER_CLICK\x10)\x12\x10\n" +
	"\fBROWSER_TYPE\x10*\x12\x13\n" +
	"\x0fBROWSER_EXTRACT\x10+\x12\x16\n" +
	"\x12BROWSER_SCREENSHOT\x10,\x12\x13\n" +
	"\x0fCREATE_SCHEDULE\x102\x12\x13\n" +
	"\x0fDELETE_SCHEDULE\x103\x12\x12\n" +
	"\x0eLIST_SCHEDULES\x104\x12\x11\n" +
	"\rREAD_CALENDAR\x10<\x12\x10\n" +
	"\fCREATE_EVENT\x10=\x12\x10\n" +
	"\fUPDATE_EVENT\x10>\x12\x10\n" +
	"\fDELETE_EVENT\x10?\x12\x0e\n" +
	"\n" +
	"GIT_STATUS\x10F\x12\f\n" +
	"\bGIT_DIFF\x10G\x12\x0e\n" +
	"\n" +
	"GIT_COMMIT\x10H\x12\f\n" +
	"\bGIT_PUSH\x10I\x12\f\n" +
	"\bGIT_PULL\x10J\x12\v\n" +
	"\aGIT_LOG\x10K\x12\x0e\n" +
	"\n" +
	"GIT_BRANCH\x10L\x12\x10\n" +
	"\fGIT_CHECKOUT\x10M\x12\x10\n" +
	"\fMEMORY_WRITE\x10P\x12\x11\n" +
	"\rMEMORY_SEARCH\x10Q\x12\x11\n" +
	"\rCANVAS_CREATE\x10Z\x12\x11\n" +
	"\rCANVAS_UPDATE\x10[*W\n" +
	"\x0fVerdictDecision\x12 \n" +
	"\x1cVERDICT_DECISION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\x12\t\n" +
	"\x05BLOCK\x10\x02\x12\f\n" +
	"\bESCALATE\x10\x03*y\n" +
	"\x10SensitivityLevel\x12\x1b\n" +
	"\x17SENSITIVITY_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x01\x12\f\n" +
	"\bINTERNAL\x10\x02\x12\x10\n" +
	"\fCONFIDENTIAL\x10\x03\x12\x0e\n" +
	"\n" +
	"RESTRICTED\x10\x04\x12\f\n" +
	"\bCRITICAL\x10\x05*\x9d\x02\n" +
	"\bGoalType\x12\x19\n" +
	"\x15GOAL_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFILE_MANAGEMENT\x10\x01\x12\x12\n" +
	"\x0eCODE_EXECUTION\x10\x02\x12\x11\n" +
	"\rCOMMUNICATION\x10\x03\x12\x19\n" +
	"\x15INFORMATION_RETRIEVAL\x10\x04\x12\x0e\n" +
	"\n" +
	"SCHEDULING\x10\x05\x12\x0f\n" +
	"\vNOTE_TAKING\x10\x06\x12\x10\n" +
	"\fWEB_BROWSING\x10\a\x12\x12\n" +
	"\x0eGIT_OPERATIONS\x10\b\x12\x13\n" +
	"\x0fTEXT_PROCESSING\x10\t\x12\x15\n" +
	"\x11SYSTEM_MANAGEMENT\x10\n" +
	"\x12\f\n" +
	"\bCREATIVE\x10\v\x12\x10\n" +
	"\fCONVERSATION\x10\f\x12\f\n" +
	"\bCALENDAR\x10\r*@\n" +
	"\vSessionMode\x12\x1c\n" +
	"\x18SESSION_MODE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\a\n" +
	"\x03OTR\x10\x02*\xad\x03\n" +
	"\x0eAuditEventType\x12\x1b\n" +
	"\x17AUDIT_EVENT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACTION_PROPOSED\x10\x01\x12\x14\n" +
	"\x10ACTION_EVALUATED\x10\x02\x12\x13\n" +
	"\x0fACTION_APPROVED\x10\x03\x12\x12\n" +
	"\x0eACTION_BLOCKED\x10\x04\x12\x13\n" +
	"\x0fACTION_EXECUTED\x10\x05\x12\x11\n" +
	"\rACTION_FAILED\x10\x06\x12\x10\n" +
	"\fSHIELD_ERROR\x10\a\x12\x13\n" +
	"\x0fCANARY_VERIFIED\x10\b\x12\x12\n" +
	"\x0eCANARY_MISSING\x10\t\x12\x12\n" +
	"\x0eRATE_LIMIT_HIT\x10\n" +
	"\x12\x14\n" +
	"\x10BUDGET_EXHAUSTED\x10\v\x12\x13\n" +
	"\x0fSELF_PROTECTION\x10\f\x12\x15\n" +
	"\x11TRANSACTION_BEGIN\x10\r\x12\x16\n" +
	"\x12TRANSACTION_COMMIT\x10\x0e\x12\x18\n" +
	"\x14TRANSACTION_ROLLBACK\x10\x0f\x12\x17\n" +
	"\x13INTEGRITY_VIOLATION\x10\x10\x12\x13\n" +
	"\x0fSESSION_STARTED\x10\x11\x12\x11\n" +
	"\rSESSION_ENDED\x10\x12B8Z6github.com/openparallax/openparallax/internal/types/pbb\x06proto3"

var (
	file_openparallax_v1_types_proto_rawDescOnce sync.Once
	file_openparallax_v1_types_proto_rawDescData []byte
)

func file_openparallax_v1_types_proto_rawDescGZIP() []byte {
	file_openparallax_v1_types_proto_rawDescOnce.Do(func() {
		file_openparallax_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openparallax_v1_types_proto_rawDesc), len(file_openparallax_v1_types_proto_rawDesc)))
	})
	return file_openparallax_v1_types_proto_rawDescData
}

var file_openparallax_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_openparallax_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_openparallax_v1_types_proto_goTypes = []any{
	(ActionType)(0),            // 0: openparallax.v1.ActionType
	(VerdictDecision)(0),       // 1: openparallax.v1.VerdictDecision
	(SensitivityLevel)(0),      // 2: openparallax.v1.SensitivityLevel
	(GoalType)(0),              // 3: openparallax.v1.GoalType
	(SessionMode)(0),           // 4: openparallax.v1.SessionMode
	(AuditEventType)(0),        // 5: openparallax.v1.AuditEventType
	(*Verdict)(nil),            // 6: openparallax.v1.Verdict
	(*ActionRequest)(nil),      // 7: openparallax.v1.ActionRequest
	(*DataClassification)(nil), // 8: openparallax.v1.DataClassification
	(*StructuredIntent)(nil),   // 9: openparallax.v1.StructuredIntent
	(*ActionResult)(nil),       // 10: openparallax.v1.ActionResult
	(*Artifact)(nil),           // 11: openparallax.v1.Artifact
	(*AuditEntry)(nil),         // 12: openparallax.v1.AuditEntry
	nil,                        // 13: openparallax.v1.ActionRequest.PayloadEntry
	nil,                        // 14: openparallax.v1.StructuredIntent.ParametersEntry
}
var file_openparallax_v1_types_proto_depIdxs = []int32{
	1,  // 0: openparallax.v1.Verdict.decision:type_name -> openparallax.v1.VerdictDecision
	0,  // 1: openparallax.v1.ActionRequest.type:type_name -> openparallax.v1.ActionType
	13, // 2: openparallax.v1.ActionRequest.payload:type_name -> openparallax.v1.ActionRequest.PayloadEntry
	8,  // 3: openparallax.v1.ActionRequest.data_classification:type_name -> openparallax.v1.DataClassification
	2,  // 4: openparallax.v1.DataClassification.sensitivity:type_name -> openparallax.v1.SensitivityLevel
	3,  // 5: openparallax.v1.StructuredIntent.goal:type_name -> openparallax.v1.GoalType
	0,  // 6: openparallax.v1.StructuredIntent.primary_action:type_name -> openparallax.v1.ActionType
	14, // 7: openparallax.v1.StructuredIntent.parameters:type_name -> openparallax.v1.StructuredIntent.ParametersEntry
	2,  // 8: openparallax.v1.StructuredIntent.sensitivity:type_name -> openparallax.v1.SensitivityLevel
	11, // 9: openparallax.v1.ActionResult.artifact:type_name -> openparallax.v1.Artifact
	5,  // 10: openparallax.v1.AuditEntry.event_type:type_name -> openparallax.v1.AuditEventType
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_openparallax_v1_types_proto_init() }
func file_openparallax_v1_types_proto_init() {
	if File_openparallax_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openparallax_v1_types_proto_rawDesc), len(file_openparallax_v1_types_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openparallax_v1_types_proto_goTypes,
		DependencyIndexes: file_openparallax_v1_types_proto_depIdxs,
		EnumInfos:         file_openparallax_v1_types_proto_enumTypes,
		MessageInfos:      file_openparallax_v1_types_proto_msgTypes,
	}.Build()
	File_openparallax_v1_types_proto = out.File
	file_openparallax_v1_types_proto_goTypes = nil
	file_openparallax_v1_types_proto_depIdxs = nil
}
